"""Bounded empirical recovery estimates, independent of source and equipment control.

An episode observes recovery under the installed system's actual operating
conditions. Its fitted rate is not delivered heat, building capacity, or COP.
The caller owns observation quality, comfort tolerance, and per-zone isolation.
"""

from __future__ import annotations

from dataclasses import dataclass, replace
from math import isfinite
from statistics import fmean, median
from typing import Literal

from .model import Mode

DAY = 86400.0
RETENTION_SECONDS = 30 * DAY
MAX_EPISODES = 128
MIN_EPISODES = 10
MIN_VALIDATIONS = 3
MIN_HISTORY_SECONDS = 7 * DAY
MAX_IDLE_SECONDS = 7 * DAY
INDEPENDENCE_SECONDS = 6 * 3600.0
MIN_DEFICIT = 0.2
WEATHER_RADIUS = 3.0

type RecoveryOutcome = Literal["reached", "failed", "censored"]


@dataclass(frozen=True, slots=True)
class RecoveryEpisode:
    """A finished episode; outdoor temperature is the observation at its start.

    ``predicted_seconds`` is the actual advisory forecast captured by the adapter.
    The two validation forecasts are generated by ``record_episode`` from prior
    episodes only, before the new outcome can enter the training history.
    """

    mode: Mode
    started_at: float
    ended_at: float
    deficit: float
    outcome: RecoveryOutcome
    outdoor_temperature: float | None = None
    predicted_seconds: float | None = None
    reason: str | None = None
    baseline_predicted_seconds: float | None = None
    weather_predicted_seconds: float | None = None

    @property
    def elapsed_seconds(self) -> float:
        return self.ended_at - self.started_at


@dataclass(frozen=True, slots=True)
class ThermalModel:
    """Immutable bounded observations for one zone, with separate modes."""

    episodes: tuple[RecoveryEpisode, ...] = ()


@dataclass(frozen=True, slots=True)
class RecoveryEstimate:
    """A shadow prediction unless confidence permits an explicitly opted-in policy.

    A provisional ``seconds`` value is useful for later validation, but never
    authorizes active planning. Every accepted estimate has an expiry deadline.
    """

    seconds: float | None
    confidence: bool
    status: str
    reason: str
    episode_count: int = 0
    validation_count: int = 0
    error_seconds: float | None = None
    valid_until: float | None = None
    rate_celsius_per_hour: float | None = None
    startup_delay_seconds: float | None = None
    weather_adjusted: bool = False


@dataclass(frozen=True, slots=True)
class _Candidate:
    seconds_per_degree: float
    delay: float
    low: float
    high: float

    def predict(self, deficit: float) -> float | None:
        if not self.low <= deficit <= self.high:
            return None
        return self.delay + deficit * self.seconds_per_degree


def recovery_deficit(mode: Mode, target: float, temperature: float) -> float:
    """Return the directional deficit; callers apply their existing comfort tolerance."""
    if not isfinite(target) or not isfinite(temperature) or mode is Mode.OFF:
        return 0.0
    return max(0.0, target - temperature if mode is Mode.HEAT else temperature - target)


def _valid(episode: RecoveryEpisode) -> bool:
    return (
        episode.mode in (Mode.HEAT, Mode.COOL)
        and episode.outcome in ("reached", "failed", "censored")
        and all(isfinite(x) for x in (episode.started_at, episode.ended_at, episode.deficit))
        and 0 < episode.elapsed_seconds <= DAY
        and MIN_DEFICIT <= episode.deficit <= 10
        and (
            episode.outdoor_temperature is None
            or isfinite(episode.outdoor_temperature)
            and -60 <= episode.outdoor_temperature <= 60
        )
    )


def _recent(model: ThermalModel, now: float) -> tuple[RecoveryEpisode, ...]:
    return tuple(
        sorted(
            (
                episode
                for episode in model.episodes
                if _valid(episode) and now - RETENTION_SECONDS < episode.ended_at <= now
            ),
            key=lambda episode: (episode.started_at, episode.ended_at),
        )[-MAX_EPISODES:]
    )


def _independent(episodes: tuple[RecoveryEpisode, ...], mode: Mode) -> tuple[RecoveryEpisode, ...]:
    selected: list[RecoveryEpisode] = []
    for episode in episodes:
        if episode.mode is not mode:
            continue
        if selected and (
            episode.started_at - selected[-1].started_at < INDEPENDENCE_SECONDS
            or episode.started_at < selected[-1].ended_at
        ):
            continue
        selected.append(episode)
    return tuple(selected)


def _usable(episode: RecoveryEpisode) -> bool:
    return (
        episode.outcome == "reached"
        and episode.elapsed_seconds >= 300
        and 0.01 <= 3600 * episode.deficit / episode.elapsed_seconds <= 10
    )


def _weighted_median(values: list[tuple[float, float]]) -> float:
    ordered = sorted(values)
    halfway = sum(weight for _, weight in ordered) / 2
    accumulated = 0.0
    for value, weight in ordered:
        accumulated += weight
        if accumulated >= halfway:
            return value
    return ordered[-1][0]  # Rounding can leave the cumulative sum short.


def _fit(episodes: tuple[RecoveryEpisode, ...], now: float) -> _Candidate | None:
    usable = tuple(episode for episode in episodes if _usable(episode))
    if len(usable) < 3:
        return None
    # Halving evidence weight every fortnight makes drift gradual, while the
    # hard retention limit keeps both computation and stored history bounded.
    weights = [2 ** (-(now - episode.ended_at) / (14 * DAY)) for episode in usable]
    slope = _weighted_median(
        [
            (episode.elapsed_seconds / episode.deficit, weight)
            for episode, weight in zip(usable, weights, strict=True)
        ]
    )
    low = min(episode.deficit for episode in usable)
    high = max(episode.deficit for episode in usable)
    candidate = _Candidate(slope, 0.0, low, high)
    if high - low >= 0.5:
        pairs = [
            (
                (right.elapsed_seconds - left.elapsed_seconds) / (right.deficit - left.deficit),
                min(weights[i], weights[j]),
            )
            for i, left in enumerate(usable)
            for j, right in enumerate(usable)
            if j > i and abs(right.deficit - left.deficit) >= 0.2
        ]
        if pairs:
            fitted_slope = _weighted_median(pairs)
            delay = _weighted_median(
                [
                    (episode.elapsed_seconds - fitted_slope * episode.deficit, weight)
                    for episode, weight in zip(usable, weights, strict=True)
                ]
            )
            baseline_error = median(
                abs(episode.elapsed_seconds - slope * episode.deficit) for episode in usable
            )
            delayed_error = median(
                abs(episode.elapsed_seconds - delay - fitted_slope * episode.deficit)
                for episode in usable
            )
            if (
                360 <= fitted_slope <= 72000
                and 0 < delay <= 6 * 3600
                and baseline_error > 0
                and delayed_error <= baseline_error * 0.8
            ):
                candidate = _Candidate(fitted_slope, delay, low, high)
    return candidate if 360 <= candidate.seconds_per_degree <= 72000 else None


def _weather_episodes(
    episodes: tuple[RecoveryEpisode, ...], outdoor: float
) -> tuple[RecoveryEpisode, ...]:
    nearby = tuple(
        episode
        for episode in episodes
        if episode.outdoor_temperature is not None
        and abs(episode.outdoor_temperature - outdoor) <= WEATHER_RADIUS
    )
    temperatures = [
        episode.outdoor_temperature for episode in nearby if episode.outdoor_temperature is not None
    ]
    if not temperatures or not min(temperatures) <= outdoor <= max(temperatures):
        return ()
    return nearby


def _shadow(
    episodes: tuple[RecoveryEpisode, ...], episode: RecoveryEpisode, *, weather: bool
) -> float | None:
    prior = _independent(
        tuple(
            earlier
            for earlier in episodes
            if episode.started_at - RETENTION_SECONDS < earlier.ended_at <= episode.started_at
        ),
        episode.mode,
    )
    if weather:
        if episode.outdoor_temperature is None:
            return None
        prior = _weather_episodes(prior, episode.outdoor_temperature)
    complete = tuple(earlier for earlier in prior if _usable(earlier))
    if not complete or episode.started_at >= complete[-1].ended_at + MAX_IDLE_SECONDS:
        return None
    candidate = _fit(prior, episode.started_at)
    return None if candidate is None else candidate.predict(episode.deficit)


def record_episode(model: ThermalModel, episode: RecoveryEpisode, now: float) -> ThermalModel:
    """Retain an outcome and its strictly prior-heldout validation forecasts.

    Invalid optional telemetry is discarded. Repeated or overlapping episodes
    never increase the independent evidence count, and a recorded observation
    cannot be overwritten by a later successful version of the same attempt.
    """
    if not isfinite(now):
        return model
    recent = _recent(model, now)
    if not _valid(episode) or not now - RETENTION_SECONDS < episode.ended_at <= now:
        return ThermalModel(recent)
    if any(old.mode is episode.mode and old.started_at == episode.started_at for old in recent):
        return ThermalModel(recent)
    episode = replace(
        episode,
        baseline_predicted_seconds=_shadow(recent, episode, weather=False),
        weather_predicted_seconds=_shadow(recent, episode, weather=True),
    )
    return ThermalModel(_recent(ThermalModel((*recent, episode)), now))


def _quality(
    episodes: tuple[RecoveryEpisode, ...], *, weather: bool
) -> tuple[bool, str, int, float | None]:
    usable = tuple(episode for episode in episodes if _usable(episode))
    predictions = [
        (episode, prediction)
        for episode in episodes
        if (
            prediction := (
                episode.weather_predicted_seconds if weather else episode.baseline_predicted_seconds
            )
        )
        is not None
        and isfinite(prediction)
        and prediction > 0
    ]
    errors = [
        abs(episode.elapsed_seconds - prediction)
        for episode, prediction in predictions
        if _usable(episode)
    ]
    error = fmean(errors) if errors else None
    if len(usable) < MIN_EPISODES:
        return False, "fewer than 10 independent complete episodes", len(predictions), error
    if usable[-1].started_at - usable[0].started_at < MIN_HISTORY_SECONDS:
        return False, "less than 7 days of independent recovery history", len(predictions), error
    failures = sum(not _usable(episode) for episode in episodes)
    if failures / len(episodes) > 0.2 or any(not _usable(episode) for episode in episodes[-3:]):
        return False, "failed or censored recoveries reduce confidence", len(predictions), error
    complete_predictions = [
        (episode, prediction) for episode, prediction in predictions if _usable(episode)
    ]
    if len(complete_predictions) < MIN_VALIDATIONS:
        return False, "fewer than 3 prior-heldout recovery predictions", len(predictions), error
    accurate = sum(
        abs(episode.elapsed_seconds - prediction) <= max(300.0, 0.2 * episode.elapsed_seconds)
        for episode, prediction in predictions
        if _usable(episode)
    )
    if accurate / len(predictions) < 0.8 or (
        error is not None
        and error
        > max(600.0, 0.2 * fmean(episode.elapsed_seconds for episode, _ in complete_predictions))
    ):
        return False, "prior-heldout recovery prediction error is too high", len(predictions), error
    return True, "validated independent recovery history", len(predictions), error


def _weather_improves(episodes: tuple[RecoveryEpisode, ...]) -> bool:
    comparable = [
        episode
        for episode in episodes
        if _usable(episode)
        and episode.baseline_predicted_seconds is not None
        and episode.weather_predicted_seconds is not None
    ]
    if len(comparable) < MIN_VALIDATIONS:
        return False
    baseline = fmean(
        abs(episode.elapsed_seconds - episode.baseline_predicted_seconds)
        for episode in comparable
        if episode.baseline_predicted_seconds is not None
    )
    weather = fmean(
        abs(episode.elapsed_seconds - episode.weather_predicted_seconds)
        for episode in comparable
        if episode.weather_predicted_seconds is not None
    )
    return weather + 60 <= baseline and weather <= baseline * 0.8


def estimate(
    model: ThermalModel,
    mode: Mode,
    deficit: float,
    now: float,
    outdoor_temperature: float | None = None,
) -> RecoveryEstimate:
    """Return bounded recovery time with evidence, fallback reason, and expiry.

    Weather is used only when nearby observed conditions contain enough history
    and independently improve later predictions. Missing or sparse weather
    evidence leaves the learned baseline available. No estimate commands anything.
    """
    if mode is Mode.OFF or not isfinite(deficit) or not isfinite(now):
        return RecoveryEstimate(None, False, "unavailable", "invalid mode, deficit, or time")
    if deficit <= 0:
        return RecoveryEstimate(0.0, False, "satisfied", "no recovery deficit")
    episodes = _independent(_recent(model, now), mode)
    if not episodes:
        return RecoveryEstimate(None, False, "collecting", "no independent recovery history")
    usable = tuple(episode for episode in episodes if _usable(episode))
    count = len(usable)
    if not usable or now >= usable[-1].ended_at + MAX_IDLE_SECONDS:
        return RecoveryEstimate(None, False, "stale", "no recent complete recovery", count)
    candidate = _fit(episodes, now)
    if candidate is None:
        return RecoveryEstimate(
            None, False, "collecting", "insufficient plausible recovery data", count
        )
    seconds = candidate.predict(deficit)
    if seconds is None:
        return RecoveryEstimate(
            None, False, "out_of_range", "deficit outside observed range", count
        )
    confidence, reason, validations, error = _quality(episodes, weather=False)
    selected = episodes
    weather_adjusted = False
    if outdoor_temperature is not None and isfinite(outdoor_temperature):
        nearby = _weather_episodes(episodes, outdoor_temperature)
        weather_candidate = _fit(nearby, now)
        quality = _quality(nearby, weather=True)
        if weather_candidate is not None and quality[0] and _weather_improves(nearby):
            weather_seconds = weather_candidate.predict(deficit)
            if weather_seconds is not None:
                candidate, seconds, selected = weather_candidate, weather_seconds, nearby
                confidence, reason, validations, error = quality
                count = sum(_usable(episode) for episode in nearby)
                weather_adjusted = True
                reason = "weather conditions improve prior-heldout recovery predictions"
    expiry = min(
        min(episode.ended_at for episode in selected) + RETENTION_SECONDS,
        max(episode.ended_at for episode in selected if _usable(episode)) + MAX_IDLE_SECONDS,
    )
    return RecoveryEstimate(
        seconds,
        confidence,
        "ready" if confidence else "collecting",
        reason,
        count,
        validations,
        error,
        expiry,
        3600 / candidate.seconds_per_degree,
        candidate.delay,
        weather_adjusted,
    )
